import Foundation

// MARK: - EventBus
//
// Central typed event bus. Observers publish events; handlers react without polling.
// Every component in Sotto is a sleeping subscriber — it only wakes when something happens.
//
// Usage:
//   Publishing:  await EventBus.shared.emit(.batteryLow(percent: 12))
//   Subscribing: for await event in EventBus.shared.makeStream() { … }

actor EventBus {
    static let shared = EventBus()
    private var continuations: [UUID: AsyncStream<Event>.Continuation] = [:]

    // MARK: - Event catalog

    enum Event: Sendable {
        // Input
        case userSpoke(String)

        // System
        case clipboardChanged(content: String, kind: ClipboardKind)
        case fileArrived(url: URL, ext: String)
        case batteryLow(percent: Int)
        case batteryCharging(percent: Int)
        case networkChanged(isOnline: Bool)
        case appLaunched(name: String, bundleID: String)

        // Calendar
        case calendarEventSoon(title: String, minutesAway: Int, attendees: [String])

        // Agent
        case missionStarted(id: String, goal: String)
        case missionCompleted(id: String, summary: String)
        case missionFailed(id: String, reason: String)
        case skillEnabled(name: String, trigger: String)
        case skillDrafted(name: String, description: String)

        // Conversation (drives cross-turn continuity — see ConversationMemory)
        case conversationTurn(user: String, assistant: String)

        // Proactive suggestions (generated by observers, shown to user)
        case suggestionReady(message: String, command: String?)
    }

    enum ClipboardKind: Sendable {
        case githubURL(String)
        case gitlabURL(String)
        case genericURL(String)
        case errorMessage
        case code(language: String)
        case plainText
        case image
    }

    // MARK: - Pub/Sub

    /// Emit an event to all subscribers.
    func emit(_ event: Event) {
        for c in continuations.values { c.yield(event) }
        logEvent(event)
    }

    /// Returns an `AsyncStream` that delivers events to the caller.
    ///
    /// Actor-isolated (callers `await`) so the subscriber is registered *synchronously*
    /// during stream construction — there is no window between handing back the stream
    /// and being subscribed in which an emitted event could be silently dropped.
    ///
    /// The buffer is bounded to the newest 32 events: for HUD/voice notifications a
    /// slow consumer should see the latest state, not an unbounded backlog that grows
    /// memory on an 8 GB machine.
    func makeStream() -> AsyncStream<Event> {
        let id = UUID()
        // `makeStream` hands back the continuation directly (no @Sendable build
        // closure), so we can register it synchronously here on the actor —
        // race-free relative to `emit`.
        let (stream, continuation) = AsyncStream<Event>.makeStream(bufferingPolicy: .bufferingNewest(32))
        continuations[id] = continuation
        continuation.onTermination = { _ in
            Task { await EventBus.shared.removeSubscriber(id: id) }
        }
        return stream
    }

    // MARK: - Private

    private func removeSubscriber(id: UUID) {
        continuations[id]?.finish()
        continuations.removeValue(forKey: id)
    }

    private func logEvent(_ event: Event) {
        let label: String
        switch event {
        case .clipboardChanged(_, let kind): label = "clipboard.\(kind)"
        case .fileArrived(let url, _):       label = "file.\(url.lastPathComponent)"
        case .batteryLow(let p):             label = "battery.low(\(p)%)"
        case .batteryCharging(let p):        label = "battery.charging(\(p)%)"
        case .calendarEventSoon(let t, let m, _): label = "calendar.\(t)(\(m)min)"
        case .missionCompleted(let id, _):   label = "mission.done(\(id.prefix(8)))"
        case .missionFailed(let id, _):      label = "mission.failed(\(id.prefix(8)))"
        case .suggestionReady(let msg, _):   label = "suggestion.\(msg.prefix(30))"
        case .skillEnabled(let n, _):        label = "skill.enabled.\(n)"
        default:                             label = "\(event)"
        }
        print("[EVENTBUS] \(label)")
    }
}
